<?php

namespace App\Observers;

use App\Models\Ledger;
use App\Models\PinCode;
use App\Models\User;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Str;

class PinCodeObserver
{
    /**
     * Handle the PinCode "created" event.
     */
    public function created(PinCode $pinCode): void
    {
        $admin = Auth::guard('admin')->user();
        if ($admin) {
            $pinCode->admin_id = $admin->id;
            $this->addLedger($pinCode);
        } else {
            $user = Auth::user();
            if ($user) {
                $pinCode->user_id = $user->id;
                $this->addLedger($pinCode, $user);
            }
        }
        $pinCode->save();

    }

    /**
     * Handle the PinCode "updated" event.
     */
    public function updated(PinCode $pinCode): void
    {
        //
    }

    /**
     * Handle the PinCode "deleted" event.
     */
    public function deleted(PinCode $pinCode): void
    {
        //
    }

    /**
     * Handle the PinCode "restored" event.
     */
    public function restored(PinCode $pinCode): void
    {
        //
    }

    /**
     * Handle the PinCode "force deleted" event.
     */
    public function forceDeleted(PinCode $pinCode): void
    {
        //
    }

    /**
     * Add ledger record
     */
    private function addLedger(PinCode $pinCode, User $user = null)
    {
        $ledger = new Ledger();
        $ledger->pin_code = $pinCode->id;
        $ledger->transaction_number = Str::uuid();
        $ledger->withdraw = $pinCode->amount;
        if($user){
            $ledger->user_id = $user->id;
            $ledger->note = "Pin generated by: " . $user->name;
        }else{
            $ledger->note = "Pin generated by staff: " . auth()->guard('admin')->user()->name;
        }
        $ledger->save();
    }
}
