@extends('components.layouts.app')

@section('content')
    @include('partials.page-header', [
        'title' => 'View Pin',
        'breadcrumbs' => [
            ['text' => 'Dashboard', 'link' => route('dashboard')],
            ['text' => 'Pin Code List', 'link' => route('pins.index')],
            ['text' => 'View', 'link' => null],
        ],
    ])

    <div class="row">
        <div class="col-md-3">
            <div class="card" style="height: calc(100% - 15px)">
                <div class="card-body">
                    <small class="d-block">Pin</small>
                    <strong>{{ $pin->pin_code }}</strong>
                </div>
                {{-- /.card-body --}}
            </div>
            {{-- /.card --}}
        </div>
        {{-- /.col --}}
        <div class="col-md-3">
            <div class="card" style="height: calc(100% - 15px)">
                <div class="card-body">
                    <small class="d-block">Amount</small>
                    <strong>
                        {{ currency(DiligentCreators('currency'), ['symbol'])['symbol'] }}
                        {{ $pin->amount }}
                        {{ currency(DiligentCreators('currency'), ['name'])['name'] }}
                    </strong>
                </div>
                {{-- /.card-body --}}
            </div>
            {{-- /.card --}}
        </div>
        {{-- /.col --}}
        <div class="col-md-3">
            <div class="card" style="height: calc(100% - 15px)">
                <div class="card-body">
                    <small class="d-block">Generated By</small>
                    @if ($pin->user_id)
                        <strong>{{ $pin->user->name }}</strong>
                    @endif
                    @if ($pin->admin_id)
                        <a href="{{ route('admin.staff.show', $pin->admin_id) }}">
                            <strong>{{ $pin->admin->name }}</strong>
                        </a>
                    @endif
                </div>
                {{-- /.card-body --}}
            </div>
            {{-- /.card --}}
        </div>
        {{-- /.col --}}
        <div class="col-md-3">
            <div class="card" style="height: calc(100% - 15px)">
                <div class="card-body">
                    <small class="d-block">Status</small>
                    @if ($pin->is_used)
                        <strong class="badge bg-success">Used</strong>
                    @else
                        <strong class="badge bg-danger">Unused</strong>
                    @endif
                </div>
                {{-- /.card-body --}}
            </div>
            {{-- /.card --}}
        </div>
        {{-- /.col --}}
    </div>

    {{-- /.row --}}
    <div class="row">
        <div class="col-md-3">
            <div class="card" style="height: calc(100% - 15px)">
                <div class="card-body">
                    <small class="d-block">Used By</small>
                    @if ($pin->used_by)
                        <strong>{{ $pin->usedBy->name }}</strong>
                    @else
                        <strong>-</strong>
                    @endif
                </div>
                {{-- /.card-body --}}
            </div>
            {{-- /.card --}}
        </div>
        {{-- /.col --}}
        <div class="col-md-3">
            <div class="card" style="height: calc(100% - 15px)">
                <div class="card-body">
                    <small class="d-block">Used At</small>
                    @if ($pin->used_at)
                        {{ $pin->used_at->diffForHumans() }}
                        <small class="d-block">{{ $pin->used_at->format('l, F j, Y h:i A') }}</small>
                    @else
                        <small>Never</small>
                    @endif
                </div>
                {{-- /.card-body --}}
            </div>
            {{-- /.card --}}
        </div>
        {{-- /.col --}}
        <div class="col-md-3">
            <div class="card" style="height: calc(100% - 15px)">
                <div class="card-body">
                    <small class="d-block">Created At</small>
                    {{ $pin->created_at->diffForHumans() }}
                    <small class="d-block">{{ $pin->created_at->format('l, F j, Y h:i A') }}</small>
                </div>
                {{-- /.card-body --}}
            </div>
            {{-- /.card --}}
        </div>
        {{-- /.col --}}
        <div class="col-md-3">
            <div class="card" style="height: calc(100% - 15px)">
                <div class="card-body">
                    <small class="d-block">Updated At</small>
                    {{ $pin->updated_at->diffForHumans() }}
                    <small class="d-block">{{ $pin->updated_at->format('l, F j, Y h:i A') }}</small>
                </div>
                {{-- /.card-body --}}
            </div>
            {{-- /.card --}}
        </div>
        {{-- /.col --}}
    </div>
    {{-- /.row --}}
@endsection

@push('styles')
@endpush

@push('scripts')
    <script></script>
@endpush
