@extends('components.layouts.app')

@section('content')
    @include('partials.page-header', [
        'title' => 'View Pin',
        'breadcrumbs' => [
            ['text' => 'Dashboard', 'link' => route('admin.dashboard')],
            ['text' => 'View List', 'link' => route('admin.pins.index')],
            ['text' => 'View', 'link' => null],
        ],
    ])

    <div class="row">
        <div class="col-md-3">
            <div class="card" style="height: calc(100% - 15px)">
                <div class="card-body">
                    <small class="d-block">Pin</small>
                    <strong>{{ $pin->pin }}</strong>
                </div>
                {{-- /.card-body --}}
            </div>
            {{-- /.card --}}
        </div>
        {{-- /.col --}}
        <div class="col-md-3">
            <div class="card" style="height: calc(100% - 15px)">
                <div class="card-body">
                    <small class="d-block">Amount</small>
                    <strong>
                        {{ currency(DiligentCreators('currency'), ['symbol'])['symbol'] }}
                        {{ $pin->amount }}
                        {{ currency(DiligentCreators('currency'),['name'])['name'] }}
                    </strong>
                </div>
                {{-- /.card-body --}}
            </div>
            {{-- /.card --}}
        </div>
        {{-- /.col --}}
        <div class="col-md-3">
            <div class="card" style="height: calc(100% - 15px)">
                <div class="card-body">
                    <small class="d-block">Generated By</small>
                    @if ($pin->user_id)
                        <a href="{{ route('admin.users.show', $pin->user_id) }}">
                            <strong>{{ $pin->user->name }}</strong>
                        </a>
                    @endif
                    @if ($pin->admin_id)
                        <a href="{{ route('admin.staff.show', $pin->admin_id) }}">
                            <strong>{{ $pin->admin->name }}</strong>
                        </a>
                    @endif
                </div>
                {{-- /.card-body --}}
            </div>
            {{-- /.card --}}
        </div>
        {{-- /.col --}}
        <div class="col-md-3">
            <div class="card" style="height: calc(100% - 15px)">
                <div class="card-body">
                    <small class="d-block">Status</small>
                    @if ($pin->is_used)
                        <strong class="badge bg-success">Used</strong>
                    @else
                        <strong class="badge bg-danger">Unused</strong>
                    @endif
                </div>
                {{-- /.card-body --}}
            </div>
            {{-- /.card --}}
        </div>
        {{-- /.col --}}
    </div>
    {{-- /.row --}}
@endsection

@push('styles')
@endpush

@push('scripts')
    <script></script>
@endpush
